reflector:
  fullnameOverride: reflector
  image:
    repository: emberstack/kubernetes-reflector
    pullPolicy: IfNotPresent
    tag: 9.1.17@sha256:7f8cabc16f0415d1eb7835c7d29ee2c3678d9b3ac35027e91b4ea2613a098c08
  podSecurityContext:
    fsGroup: 2000
    runAsGroup: 65532
    runAsNonRoot: true
    runAsUser: 65532
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 65532
    allowPrivilegeEscalation: false
