reflector:
  fullnameOverride: reflector
  image:
    repository: emberstack/kubernetes-reflector
    pullPolicy: IfNotPresent
    tag: 9.1.22@sha256:eed660f550b0e3288d6dfbf99d0905d1eadc5ed0435bd60045d2dd8294ee71e6
  podSecurityContext:
    fsGroup: 2000
    runAsGroup: 65532
    runAsNonRoot: true
    runAsUser: 65532
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 65532
    allowPrivilegeEscalation: false
