reflector:
  fullnameOverride: reflector
  image:
    repository: emberstack/kubernetes-reflector
    pullPolicy: IfNotPresent
    tag: 9.0.313@sha256:888038b7eaa9f61eef39d427b0710e0fa10895a45d202b4db3647bcee8f8f0b3
  podSecurityContext:
    fsGroup: 2000
    runAsGroup: 65532
    runAsNonRoot: true
    runAsUser: 65532
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 65532
    allowPrivilegeEscalation: false
