apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pialert
spec:
  selector:
    matchLabels:
      app: pialert
  serviceName: pialert
  replicas: 1
  podManagementPolicy: Parallel
  revisionHistoryLimit: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pialert
    spec:
      hostNetwork: true
      containers:
      - name: pialert
        image: jokobsk/pi.alert:24.10.12@sha256:6289614106498dba9ddc6e226c59ade8117b9f148f70ca87752bd2041db2d915
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
        env:
          - name: TZ
            value: America/Los_Angeles
          - name: PORT
            value: "20211"
        ports:
        - containerPort: 20211
          name: http
        volumeMounts:
        - name: pialert
          subPath: config
          mountPath: /home/pi/pialert/config
        - name: pialert
          subPath: db
          mountPath: /home/pi/pialert/db
  volumeClaimTemplates:
  - metadata:
      name: pialert
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
