apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "macvlan-conf",
              "mac": "de:45:df:64:20:21",
              "ips": ["192.168.5.131/24"],
              "gateway": ["192.168.5.1"]
            }]'
spec:
  containers:
  - name: samplepod
    command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: ubuntu@sha256:6015f66923d7afbc53558d7ccffd325d43b4e249f41a6e93eef074c9505d2233 #dougbtv/centos-network
    imagePullPolicy: IfNotPresent
